### PR TITLE
Add draft of fma notebook

### PR DESCRIPTION
**Pull request by joelostblom**
You can [download the datasets here](https://www.dropbox.com/sh/n45p72prw72czoh/AAChoPthfQMQ4-ubDDB7PJeZa?dl=0). Would make the variable names more sensible, but have to run, sorry!

### CODE REVIEW

**Comment by joelostblom** [comment]
@aays and @linamnt Just finished adding the content from today. Please have a look through before Thursday and think of what more we could do when we meet next. I included the outputs so just got to "Files changed" and click "View", you should be able to see all plots etc on GitHub.

Some of the cells have comments describing their associated task. The json data for the metrics/features [can be downloaded here](https://www.dropbox.com/s/t995wru2khdjxbq/echonest-clean.json?dl=0).

**Comment by joelostblom** [comment]
@aays I added what we did yesterday. If you have time to flesh out the descriptions somewhat and put it in the format for the project specification notebook (with the narrative and detailed descriptions), then go for it! Otherwise we can do it next time we meet. Don't worry about limit the code to only the first few tasks, we can do that as a last step when we know how everything looks.

**Comment by joelostblom** [comment]
@aays The new file ` project-description-song-classification.ipynb` contains the tasks that we think can be part of the audition file. Could you add the intro you wrote (or paste it here), and read through the tasks descriptions to see if they make senseadd to some of the task descriptions?

**Comment by aays** [comment]
@joelostblom  Submitted a PR on your fork containing the project spec so that it shows up as part of this PR post-merge... I think that's how it works, right? (Git is still confusing sometimes!)

It seems largely good to go, but a few thoughts:
- We need a catchy title - I went with 'Kick Out The Jams: Classifying Song Genres' for now, but if you guys can think of something better I'm all ears!
- I'm not sure what we should do with the 'Link to prior writing' field - do we _all_ need to attach previous writing?
- There's a TODO in there - once this PR is merged, I think we ought to link the data files where specified in the notebook
- I worry that the PCA task is better off split into two tasks - the notebook specifies that a given task should be at most 10 lines of code, and I think it makes sense to split the PCA and the plotting sections. What do you guys think?

Otherwise I think this is solid! Let me know if there's anything in the writing (overall project description, etc) you'd like to see changed.

**Comment by joelostblom** [comment]
@aays Sorry for responding late, I updated the PR and responded to many of there comments there. I like the title and the intro so well done!! Almost ready to send it!

Regarding the PCA, I think we will split it in the final version. We're cramming it in a bit here  to show more =) I feel like it should be fine, but maybe we can add a comment that the cell will be split into two.

**Comment by linamnt** [comment]
Sorry, I also lost track of these! @joelostblom thanks for fixing the issues @aays great filling in the info 
1. Title is great and intro too
3. I think we can add the a comment I can try to rewrite as well so it's more split into two (actual pca, vs plot) from the get go?

**Comment by joelostblom** [comment]
I  am merging all these files. @linamnt For emailing david, the relevant file is `fma_project_spec.ipynb`

**Pull request merged**
